dbt_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './data/duckdb_datawarehouse.duckdb'
      extensions:
        - httpfs
        - parquet
      threads: 4
      # python_path: "{{ env_var('VIRTUAL_ENV') }}/Scripts/python.exe"  # Windows path 